require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Layout/LineLength:
  Max: 130

Metrics/AbcSize:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
   Enabled: false

# Currently using OpenStructs until resources are built out
Style/OpenStructUse:
  Enabled: false
