require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Layout/LineLength:
  Max: 130
  Exclude:
    - spec/bigcommerce/v3/resources/**/*
    - spec/support/shared_examples/**/*

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 9

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/RepeatedExampleGroupDescription:
  Enabled: false

# Currently using OpenStructs until resources are built out
Style/OpenStructUse:
  Enabled: false
